(define (insert-sort vec cmp)
  (define (insert-element ele index)
    (if (< index 0)
        (begin (vector-set! vec 0 ele)
               'done)
        (if (cmp ele (vector-ref vec index))
            (begin (vector-set! vec (+ index 1) (vector-ref vec index))
                   (insert-element ele (- index 1)))
            (begin (vector-set! vec (+ index 1) ele)
                   'done))))
  (define (iter-sort k)
    (if (= k (vector-length vec))
        'done
        (begin (insert-element (vector-ref vec k) (- k 1))
               (iter-sort (+ 1 k)))))
  (iter-sort 1))
